### ISSUE TITLE
Truty breaks HTML tags

### ISSUE THREAD

**Issue by zvonicek** [mkj-is/Truty#2]
Truty in its current version breaks HTML tags. These should be probably ignored and it should format just the content of the elements.

Examples of faulty output:

`<p class=„galle­ry”><s­cript type=„tex­t/ja­vas­crip­t”>$(do­cu­men­t). …`
`<a href=„http: //farm9. staticflickr. com/8 649/15 600 540 834_fabd10d6a2_b. jpg” tar­get=„_b­lan­k”>`

**Comment by mkj-is** [comment]
That is a bit peculiar issue. Truty currently allows only plain text input. If you want to fix HTML, you should  convert only content of elements containing text. No full HTML converter is implemented yet.

I will probably write a converter for this using HTML parser like Nokogiri (http://www.nokogiri.org). Traversing HTML and choosing the right nodes to convert is not trivial task.

Was this helpful?

**Comment by zvonicek** [comment]
Yeah, I'm aware that this goes a bit farther then where your current goal is. However, if your intention is to make it usable for web (eg. Jekyll), this is crucial as in this environment the text is often interspersed with widgets and HTML tags. 

The converter would be sufficient. It would be perhaps better to handle this in _jekyll-truty_ and not to mess up _Truty_ itself with this.

**Comment by mkj-is** [comment]
Oh, I finally found what is wrong. Now I only need to find a way to fix this. Thanks for feedback.

**Comment by mkj-is** [comment]
This command line script should solve it. I will add something like this to jekyll-truty later.

``` ruby
#!/usr/bin/env ruby

require 'nokogiri'
require 'truty'

def traverse_html(node)
  node.children.each do |child|
    if child.text? && child.text.strip.length > 0 then
      child.content = Truty.fix(child.inner_text, :czech)
    else
      traverse_html(child)
    end
  end
end

file = File.open("test.html")
doc = Nokogiri::HTML(file)
file.close

traverse_html(doc)
puts doc.to_html
```

**Comment by mkj-is** [comment]
@zvonicek I updated the `jekyll-truty` tool so it does not hopefully break any HTML. Looking forward to any feedback.

**Comment by zvonicek** [comment]
@mkj-is Great job, thank you. I've already deployed it on my blog and it works nicely!

P.S. add some test cases with smileys as well, they seems to be broken. Perhaps some teenager blogspots would be nice ;-)

**Comment by zvonicek** [comment]
Oh, I've just found out there is some issue with links / _a href_ (http://norway.zvonicek.me/2015/01/11/bezkovani-v-trondheimu/).

**Comment by mkj-is** [comment]
I see. It seems to me that Kramdown and Nokogiri somehow remove whitespace before tags when combined. I will investigate later.

**Comment by mkj-is** [comment]
@zvonicek Could you please try the new versions. It should be fixed.
