### ISSUE TITLE
Incorrect conversion to №

### ISSUE THREAD

**Issue by zvonicek** [mkj-is/Truty#3]
I'd like to report a small issue with converting the sentence `je obklopeno 250 km`. The result is `je obklo­pe№250 km`, which is probably not expected.

Apart from this small hassle, it works like a charm!

**Comment by mkj-is** [comment]
@zvonicek Thanks for submitting those issues! It is really hard to think of all the possibilities. I guess I should test on more contemporary texts. Čapek is obviously not enough.
